version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      eslint:
        applies-to: version-updates
        patterns:
          - "eslint"
          - "eslint-plugin-*"
          - "@types/eslint"
          - "typescript-eslint"
          - "@stylistic/eslint-plugin"
          - "@tanstack/eslint-plugin-query"
          - "globals"
      typescript:
        applies-to: version-updates
        patterns:
          - "typescript"
          - "tslib"
      vitest:
        applies-to: version-updates
        patterns:
          - "vitest"
          - "@vitest/coverage-v8"
    ignore:
      # No major @types/node updates, since they should follow the project's
      # target node version.
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
